classes:
- cluster.{{ model }}.infra.config
parameters:
  _param:
    linux_system_codename: xenial
    reclass_data_revision: master
  linux:
    system:
      name: {{ ansible_hostname }}
      domain: local
